-- Operator Learning Assistant — SQLite Schema v2
-- Append-only system of record (except operator_synopsis which is a mutable cache).
-- Safe to re-run: CREATE TABLE IF NOT EXISTS throughout.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ── Sessions (one issue resolution = one session) ─────────────────────────────

CREATE TABLE IF NOT EXISTS sessions (
    id                  TEXT PRIMARY KEY,
    operator_id         TEXT NOT NULL,
    opened_at           TEXT NOT NULL,
    closed_at           TEXT,
    trigger_alarm_code  TEXT,
    machine_id          TEXT,
    status              TEXT NOT NULL DEFAULT 'open'
                            CHECK (status IN ('open', 'resolved', 'escalated', 'abandoned'))
);

CREATE INDEX IF NOT EXISTS idx_sessions_operator ON sessions (operator_id);
CREATE INDEX IF NOT EXISTS idx_sessions_open     ON sessions (operator_id, status)
    WHERE status = 'open';

-- ── Raw event stream — both roles (append-only, immutable) ───────────────────
-- Operator messages (role=operator) and assistant replies (role=assistant)
-- both land here. Extractor reads operator rows; Context Assembler reads all
-- rows for a session_id ordered by timestamp.

CREATE TABLE IF NOT EXISTS events (
    id                  TEXT PRIMARY KEY,
    operator_id         TEXT NOT NULL,
    session_id          TEXT NOT NULL REFERENCES sessions(id),
    role                TEXT NOT NULL CHECK (role IN ('operator', 'assistant', 'system')),
    timestamp           TEXT NOT NULL,
    shift               TEXT CHECK (shift IN ('day', 'night')),
    machine_id          TEXT,
    alarm_code          TEXT,               -- FK-in-spirit to KG AlarmCode
    event_type          TEXT NOT NULL,      -- alarm|question|task|reply|confirmation_response
    requested_modality  TEXT,
    content             TEXT NOT NULL,      -- raw message text
    outcome             TEXT CHECK (outcome IN (
                            'resolved_independently', 'escalated', 'unresolved', 'abandoned'
                        ))
);

CREATE INDEX IF NOT EXISTS idx_events_operator  ON events (operator_id);
CREATE INDEX IF NOT EXISTS idx_events_session   ON events (session_id);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events (timestamp);
CREATE INDEX IF NOT EXISTS idx_events_alarm     ON events (alarm_code);

-- ── Extracted behavioural signals (one operator event → 0..n signals) ─────────

CREATE TABLE IF NOT EXISTS signals (
    id              TEXT PRIMARY KEY,
    source_event_id TEXT NOT NULL REFERENCES events(id),
    operator_id     TEXT NOT NULL,
    category        TEXT NOT NULL CHECK (category IN (
                        'INSTRUCTION_MODALITY', 'ESCALATION', 'TROUBLESHOOTING',
                        'SHIFT_PATTERN', 'LEARNING_NEED', 'ISSUE_CONFIDENCE'
                    )),
    value           TEXT NOT NULL,
    observation     TEXT,
    timestamp       TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_signals_event    ON signals (source_event_id);
CREATE INDEX IF NOT EXISTS idx_signals_operator ON signals (operator_id);

-- ── Append-only memory-operation log (THE source of truth for the profile) ────
-- Active profile derived by folding this log; no mutable profile table.

CREATE TABLE IF NOT EXISTS memory_operations (
    id              TEXT PRIMARY KEY,
    operator_id     TEXT NOT NULL,
    op_type         TEXT NOT NULL CHECK (op_type IN ('ADD', 'REINFORCE', 'SUPERSEDE', 'NOOP')),
    target_item_id  TEXT,
    text            TEXT,               -- free-text belief content (human-facing)
    value           TEXT,               -- normalized value from signal e.g. 'VISUAL' (machine-facing)
    category        TEXT,
    source_event_id TEXT REFERENCES events(id),
    source          TEXT NOT NULL DEFAULT 'hot_path'
                        CHECK (source IN ('hot_path', 'reviewer')),
    high_weight     INTEGER NOT NULL DEFAULT 0,  -- 1 if from a confirmation response
    timestamp       TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memops_operator  ON memory_operations (operator_id);
CREATE INDEX IF NOT EXISTS idx_memops_timestamp ON memory_operations (timestamp);

-- ── Operator synopsis (mutable cache — regenerated by Reviewer, not source of truth) ─

CREATE TABLE IF NOT EXISTS operator_synopsis (
    operator_id     TEXT PRIMARY KEY,
    text            TEXT NOT NULL,
    generated_at    TEXT NOT NULL,
    source_through  TEXT,           -- latest event timestamp reflected
    version         INTEGER NOT NULL DEFAULT 1
);

-- ── Conformance events ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS conformance_events (
    id                   TEXT PRIMARY KEY,
    source_event_id      TEXT NOT NULL REFERENCES events(id),
    operator_id          TEXT NOT NULL,
    alarm_code           TEXT,
    procedure_id         TEXT,
    expected_disposition TEXT CHECK (expected_disposition IN ('SELF_RESOLVE', 'ESCALATE', 'EITHER')),
    observed_action      TEXT,
    conformance          TEXT CHECK (conformance IN ('conformant', 'divergent')),
    outcome_status       TEXT NOT NULL DEFAULT 'pending'
                             CHECK (outcome_status IN ('pending', 'resolved')),
    outcome_quality      TEXT CHECK (outcome_quality IN ('good', 'bad')),
    quadrant             TEXT,
    review_due_at        TEXT,
    reviewed             INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_conformance_operator ON conformance_events (operator_id);
CREATE INDEX IF NOT EXISTS idx_conformance_pending  ON conformance_events (outcome_status)
    WHERE outcome_status = 'pending';

-- ── Outcome measurements ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS outcomes (
    id                   TEXT PRIMARY KEY,
    conformance_event_id TEXT REFERENCES conformance_events(id),
    machine_id           TEXT NOT NULL,
    window_start         TEXT NOT NULL,
    window_end           TEXT NOT NULL,
    downtime_sec         INTEGER,
    alarm_count          INTEGER,
    peer_alarm_avg       REAL,
    recurred             INTEGER
);

-- ── Reviewer proposals ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS hypotheses (
    id               TEXT PRIMARY KEY,
    operator_id      TEXT,               -- null for collective/process-level
    kind             TEXT NOT NULL CHECK (kind IN ('behavioural_pattern', 'tacit_knowledge')),
    description      TEXT NOT NULL,
    evidence_count   INTEGER NOT NULL DEFAULT 1,
    status           TEXT NOT NULL DEFAULT 'proposed'
                         CHECK (status IN ('proposed', 'accepted', 'rejected', 'promoted')),
    source_event_ids TEXT,               -- JSON array
    created_at       TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hypotheses_operator ON hypotheses (operator_id);
CREATE INDEX IF NOT EXISTS idx_hypotheses_status   ON hypotheses (status);
